CREATE TABLE [dbo].[clientes](
[Id] [int] IDENTITY(1,1) NOT NULL,
[Nome] [VARCHAR] (10) NULL,
[Sobrenome] [VARCHAR] (15) NULL,
[email] [VARCHAR] (50) NULL,
[DataCadastro] [DATETIME] NULL,
[Ativo] [BIT] NULL,
PRIMARY KEY CLUSTERED(
	[Id] ASC
	)
	WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
	) ON [PRIMARY]
GO