CREATE TABLE [dbo].[produto](
[Id] [int] IDENTITY(1,1) NOT NULL,
[Nome] [VARCHAR] (100) NULL,
[Valor][DECIMAL] (18,2) NULL,
[Disponivel] [BIT] NULL,
[ClienteId] [INT] NULL,
PRIMARY KEY CLUSTERED(
	[Id] ASC
	)
	WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
	) ON [PRIMARY]
GO

ALTER TABLE [dbo].[produto] WITH CHECK ADD FOREIGN KEY( [ClienteId])
REFERENCES [dbo].[clientes] ([Id])
GO
